version: "2.1"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: doors-zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: doors-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "doors:1:1,doors-stats:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
